### ISSUE TITLE
Change http to https in Repository Description URL

### ISSUE THREAD

**Issue by mattt** [daveverwer/iOSDevDirectory#152]
A minor change: On the GitHub repository page for iOSDevDirectory, the website URL is <http://iosdevdirectory.com>, when it should be https://

<img width="509" alt="screen shot 2018-09-17 at 09 38 55" src="https://user-images.githubusercontent.com/7659/45613258-9a678300-ba5d-11e8-9114-7fff33350ebe.png">

**Comment by daveverwer** [comment]
Thanks, fixed 👍
