### ISSUE TITLE
Mac Development?

### ISSUE THREAD

**Issue by ConfusedVorlon** [daveverwer/iOSDevDirectory#217]
Yes - I know the title is iOS Dev Directory, but I certainly look to the iOS Dev newsletter for news on OSX development.

Should OSX Dev news not have a home?

**Comment by daveverwer** [comment]
I've been adding them in iOS development because much of the content is just as relevant. Do you have an example of one that would not fit in iOS development that would be in the new category?

**Comment by ConfusedVorlon** [comment]
It really depends on how strictly you enforce categories. 

I posted the issue because my coding category wasn't just iOS:

https://blog.hobbyistsoftware.com/category/coding/

**Comment by daveverwer** [comment]
I see, there's actually no iOS posts there at all. Just an Android one and a Mac development one. I'm reluctant to add a new category for one blog. Add it to iOS company blogs for now (it's a company site? Looks like it) and I'll split it out if it grows to become an issue later.

Thanks!

**Comment by ConfusedVorlon** [comment]
happy to go that way. Thanks for the pointer.
