### ISSUE TITLE
Enhancement - migrate to use https://github.com/johnsundell/publish

### ISSUE THREAD

**Issue by johndpope** [daveverwer/iOSDevDirectory#406]
https://www.swiftbysundell.com/

**Comment by daveverwer** [comment]
Thanks for the suggestion but I don't think it's necessary. A static site generator generates static HTML, and both Jekyll and Publish do this. There would be no difference to the end-user.

**Comment by johndpope** [comment]
a couple thousand devs may disagree - https://twitter.com/johnsundell/status/1273961662006124545?s=20

**Comment by daveverwer** [comment]
I'm afraid I do still disagree that's related to Publish. I completely agreed with what John said in that tweet. His site is lovely and truly does look and feel like a magazine, and it's lovely. What I disagree with is that Publish has anything to do with that.

What's making it look and feel like a magazine is the HTML markup and CSS, and nothing else.

Publish generates HTML and CSS.
Jekyll generates HTML and CSS.

The static site generation software is completely inconsequential to the output.
