### ISSUE TITLE
Can we add `weibo_url` field for Chinese blog's author?

### ISSUE THREAD

**Issue by ShannonChenCHN** [daveverwer/iOSDevDirectory#51]
Given that **Weibo** is the dominated social media  in China, and twitter has been  blocked in China(we could only use it by breaking the GFW).

So can we add `weibo_url` field for Chinese blog's author?

**Comment by daveverwer** [comment]
Yes, absolutely! Add `weibo_url` in the JSON and I'll get it implemented on the site.
