### ISSUE TITLE
iOS Development related YouTube channels

### ISSUE THREAD

**Issue by kristofk** [daveverwer/iOSDevDirectory#57]
There are a number of YouTube channels out there. Some well-established ones some upcoming and others are discontinued. It would be nice to list them here as `iOS Development YouTube Channels`.

**Comment by daveverwer** [comment]
I think this might work, do YouTube channels have RSS feeds? From a quick look it seems like they do. I guess they'd qualify! Pop a PR in with the ones you know of.

**Comment by kristofk** [comment]
Yeah, they have RSS feeds! But they require a little digging, [this post](https://danielmiessler.com/blog/rss-feed-youtube-channel/) shows how to acquire theme.
