### ISSUE TITLE
Add new category for Twitch streamers

### ISSUE THREAD

**Issue by Jeehut** [daveverwer/iOSDevDirectory#602]
@daveverwer  I just had the idea of adding a new category for Twitch channels after you had mentioned it in your last weekly newsletter. What do you think? Currently it seems to be relatively hard to find iOS development related Twitch streamers, your directory seems to be the perfect place for it.

Here's some streamers I'm aware of:

* https://www.twitch.tv/pilkycrc
* https://www.twitch.tv/subdigital
* https://www.twitch.tv/monsieurbee
* https://www.twitch.tv/maeganwilson_
* https://www.twitch.tv/aphluxlogix
* https://www.twitch.tv/cocoatype
* https://www.twitch.tv/aivars_meijers
* https://www.twitch.tv/drag0ndust
* https://www.twitch.tv/jeehut

**Comment by daveverwer** [comment]
It's funny you should mention this. Look what's on my Things list for tomorrow. 🤡

<img width="638" alt="Screenshot 2022-02-20 at 19 41 17@2x" src="https://user-images.githubusercontent.com/5180/154861194-f4cf696e-7cf6-47bb-82f9-47ad23fb4fa4.png">

**Comment by Jeehut** [comment]
You're the best! ❤️

**Comment by daveverwer** [comment]
Done!

https://iosdevdirectory.com/#twitch-en
https://iosdevdirectory.com/#twitch-de
