### ISSUE TITLE
iOS Dev Directory add?

### ISSUE THREAD

**Issue by razmanugget** [daveverwer/iOSDevDirectory#62]
Really, really love what you are doing with the iOS Dev Directory.  Have you thought about including paid sites like https://nsscreencast.com or http://cartoonsmart.com?  Maybe you could make a note on your site that they are paid only.

Would love to see your directory expand to encompass more resources and maybe even user reviews one day.  Not sure we need the twitter/rss feed icons.

Oh yeah, another inactive blog - https://www.natashatherobot.com

Anyway, thanks again for putting this together.

Raz

**Comment by daveverwer** [comment]
I'm not really alooking specifically to add more inactive blogs, but someone else did submit a PR with Natasha's blog in it so that's already added.

Please feel free to submit a PR with the other two sites in it, no need to mention they are paid. As long as they have RSS feeds.
