### ISSUE TITLE
Be able to endorse the sources

### ISSUE THREAD

**Issue by ivanalek** [daveverwer/iOSDevDirectory#67]
As the database grows it will become harder to extract meaningful sources from the lists. Community should be able to endorse the sources, which will prioritize them in the list.

**Comment by daveverwer** [comment]
I think this is certainly something we'll need to keep an eye on but I'm afraid the way the site is structured right now would mean this is a huge amount of work (it's a Jekyll static site at the moment) as there is no server side code being executed at all.

I'll close this for now, but let's keep an eye on it as the data set grows. Please feel free to re-open it at the point where you feel it's a problem that needs solving more urgently.
