### ISSUE TITLE
Add `mastodon_url`

### ISSUE THREAD

**Issue by nighthawk** [daveverwer/iOSDevDirectory#686]
Quite a few in the iOS community are more active on Mastodon than on Twitter these days. Mastodon's search is quite flakey, so it'd be useful if this directory also allowed adding Mastodon URLs.

**Comment by nighthawk** [comment]
Uh, follow-up idea if people then start using this: Add an option to download a list of iOS dev's on Mastodon in the CSV format Mastodon uses for importing:

```csv
Account address,Show boosts,Notify on new posts,Languages
@davew@mastodon.social,true,false,
danielpunkass@mastodon.social,true,false,
```

**Comment by daveverwer** [comment]
Yes, I have been thinking about this recently with some people moving. I don't have time to do anything about it right now, but if you want to raise a PR which adds a `mastodon_url` to your entry, that would be a good start 👍

**Comment by nighthawk** [comment]
No worries. Done. I've also added it to the schema in #687.

**Comment by daveverwer** [comment]
Thanks again Adrian. I implemented this today:

<img width="258" alt="Screenshot 2022-12-30 at 15 08 33@2x" src="https://user-images.githubusercontent.com/5180/210084830-a372314f-4aed-475e-9660-7e965b2f6789.png">

I'll do some promotion for it in the new year.

**Comment by nighthawk** [comment]
Nice. Thank you, Dave!
