### ISSUE TITLE
iOS Newsletter Section

### ISSUE THREAD

**Issue by maschall** [daveverwer/iOSDevDirectory#74]
Huge fan of iOS Dev Weekly and maybe this is a conflict of interest, but I think there should be a section for other iOS/Swift Newsletters.

https://swiftweekly.github.io/ - could be one to add.

**Comment by daveverwer** [comment]
I'd be absolutely fine with this, I did even consider including a section like this. Please feel free to create a new category in the JSON and submit a PR.
